### PR TITLE
Refactor indicator retrieval logic to use caching

### PR DESCRIPTION
**Pull request by Kaloszer**
Add simple cache

### CODE REVIEW

**Comment by cudeso** [comment]
@Kaloszer the PR is in `draft`; do you expect to update the code or can I include it? (I don't see any immediate issues with the code)

**Comment by Kaloszer** [comment]
Nah just left it in draft because einhave no way to test it atm. But if it works lgtm :d

**Review by cudeso — APPROVED** [review]

**Comment by cudeso** [comment]
NameError: name 'parsed_indicators_cache' is not defined ; rolling back

**Comment by Kaloszer** [comment]
Oh no, able to test now so I will take a look at it soon. Want to implement it internally aswell to limit runtime.

**Pull request merged**
